### ISSUE TITLE
Trying out bellperson integration with 32GiB sectors

### ISSUE THREAD

**Issue by vmx** [supranational/supra_seal#2]
I try the code from C2 into current master of `rust-fil-proofs`. The work can be found at https://github.com/filecoin-project/rust-fil-proofs/tree/sn-c2. It uses the bellperson patch from this repo, which was rebased to make it work with bellperson 0.25.0. It can be found at https://github.com/filecoin-project/bellperson/tree/sn-c2.

For 32GiB sectors, it just crashes (512MiB sectors seem to work). Steps to reproduce the problem:

Run once (it will take a while and lots of disk space, plan with 600GiB):

```console
git clone https://github.com/filecoin-project/rust-fil-proofs --branch sn-c2
cd rust-fil-proofs
RUST_LOG=trace cargo run --release --bin benchy -- window-post --size 32GiB --cache window-post-32gib-dir --preserve-cache
```

Now you can repeatedly run:

```console
RUST_LOG=trace cargo run --release --bin benchy -- window-post --size 32GiB --skip-precommit-phase1 --skip-precommit-phase2 --skip-commit-phase1 --cache /window-post-32gib-dir
```

That machine I'm running on has four Quadro RTX 6000. When I run with `CUDA_VISIBLE_DEVICES=0` so that only one GPU is available to the program, I get that error:

    terminate called without an active exception

When I run with all GPUs I get:

    terminate called after throwing an instance of 'cuda_error'
    terminate called recursively
    terminate called recursively
      what():  cudaStreamSynchronize(stream)@sppark-766e0a6fee265121/776752d/util/gpu_t.cuh:139 failed: "an illegal memory access was encountered"

**Comment by sandsentinel** [comment]
Hello,

Due to the SRS being re-usable and due to reading it being a costly operation (around 30 seconds for a 32GiB sector on the Rust side), we decoupled the proof generation and reading the SRS. When our modified proof is called, the SRS isn't passed to the C++ part of our proof from the Rust side (nor is it read). The C++ part of our proof assumes that the SRS is pre-loaded and is in memory.

We have a [read_srs](https://github.com/supranational/supra_seal/blob/main/c2/src/lib.rs#L51) function that reads an SRS file. This function must be called prior to calling our Groth16 proof. You can see an example [here](https://github.com/supranational/supra_seal/blob/main/c2/tests/c2.rs#L60). In `rust-fil-proofs`, we used to do it by inserting

```
let param_file_path = groth_params.param_file_path.to_str().unwrap().to_string();
supraseal_c2::read_srs(param_file_path);
```

after

```
let groth_params = get_stacked_params::<Tree>(porep_config)?;
```

in seal.rs, [here](https://github.com/filecoin-project/rust-fil-proofs/blob/sn-c2/filecoin-proofs/src/api/seal.rs#L504). But ideally, it should be called closer to the start of the program.

The 512MiB sector's proof worked because we have a hack in `bellperson` which only calls our modified proof when `num_circuits` is `10`.
